### ISSUE TITLE
Add version read support to Fleet provision plugin (.jar)

### ISSUE THREAD

**Issue by argandas** [aws-greengrass/aws-greengrass-fleet-provisioning-by-claim#14]
**Feature Description**
The GG Fleet provision plugin (.jar) does not support version read. 

**Use Case**
In order to validate a device manifest, it's needed to verify the GG Fleet provision plugin version. 

**Suggested implementation**
```
java -jar /GreengrassInstaller/FleetProvisioningByClaim.jar --version
AWS Greengrass Fleet Provisioning By Claim Plugin v1.1.0
```
Something similar to how we read the Greengrass Nucleus (.jar) version:
 ```
java -jar /GreengrassInstaller/lib/Greengrass.jar --version
AWS Greengrass v2.7.0
```

**Current implementation**
```
java -jar /GreengrassInstaller/FleetProvisioningByClaim.jar --version
no main manifest attribute, in /GreengrassInstaller/FleetProvisioningByClaim.jar
```

**Comment by MikeDombo** [comment]
Hi @argandas,

Fleet provisioning is a plugin to Greengrass Nucleus, as such it is not independently executable. If you're trying to validate that you have a particular version, you can download from our CloudFront, as explained here: https://docs.aws.amazon.com/greengrass/v2/developerguide/fleet-provisioning.html#download-fleet-provisioning-plugin. And use a hash algorithm, such as `sha256` in order to validate that your "device manifest" has not been modified.

**Comment by argandas** [comment]
Hey @MikeDombo, thank you so much for your quick reply, I will proceed as suggested and use the hash to verify the plugin.
